---
galaxy_info:
  author: Jussi Vaihia
  description: supervisor
  company: Futurice
  license: BSD
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
    - web
dependencies: ['futurice.pip']
  
